name: Test and Coverage

on:
  push:
    branches: [ main, crpage ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov
      - name: Run tests with coverage
        run: |
          pytest -q --cov --cov-report=xml --cov-report=term
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
      - name: Generate coverage badge
        uses: tj-actions/coverage-badge-py@v2
        with:
          output: coverage.svg
      - name: Commit coverage badge
        if: github.ref == 'refs/heads/crpage' || github.ref == 'refs/heads/main'
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add coverage.svg
          git commit -m 'chore: update coverage badge' || echo 'No changes to commit'
          git push
